# Generated by Django 6.0.2 on 2026-02-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(blank=True, default='', max_length=20)),
                ('plate_color', models.CharField(blank=True, default='yellow', max_length=20)),
                ('offense_type', models.CharField(choices=[('red_light', 'רמזור אדום'), ('phone', 'טלפון בנהיגה'), ('speeding', 'מהירות מסוכנת'), ('bypassing', 'עקיפה מסוכנת'), ('crosswalk', 'זכות קדימה במעבר חציה'), ('sidewalk_parking', 'חניה על מדרכה/מעבר חצייה'), ('bike_lane_parking', 'חניה על שביל אופניים'), ('other', 'אחר')], max_length=30)),
                ('report_date', models.DateField()),
                ('report_time', models.TimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
