# Generated by Django 6.0.2 on 2026-02-21 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_update_report_fields'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='report',
            table='report',
        ),
    ]
